### ISSUE TITLE
Bugs / Feature

### ISSUE THREAD

**Issue by withrvr** [abhiib02/PortfolioSvelte#1]
# 1. add links to emoji / icon ??
![image](https://user-images.githubusercontent.com/69628500/219866587-31ab7d74-93cc-47e3-a9ad-0e2d7eace947.png)

# 2. not looking/matching  properlyt
- just make it big ... 
- don't use orange color
![image](https://user-images.githubusercontent.com/69628500/219866719-edf2c3f6-fc5c-400f-bb41-877084805d02.png)

# 3. navbar links are too small

![image](https://user-images.githubusercontent.com/69628500/219866773-e55e195a-b045-477d-a214-287c15e70934.png)

# 4. little CSS improvement required

- that orange css 
- need more padding in label text

![image](https://user-images.githubusercontent.com/69628500/219866878-00bd577b-d29e-4b07-8d8e-12775ee47a42.png)

**Comment by withrvr** [comment]
# also .... 404 page not there

**Comment by withrvr** [comment]
add link 
![image](https://user-images.githubusercontent.com/69628500/219867701-ae3beacb-1f46-44b8-825f-74b0fb95edb3.png)

**Comment by withrvr** [comment]
![image](https://user-images.githubusercontent.com/69628500/219868148-3918d6d3-0514-4e88-90fa-ab21c60c360c.png)

wow I saw that logo animation when I opened the image in the new tab

but not showing on-site logo animation ...... properly
also make it continues/ infinite

---

also, make it clickable .... on the home page

![image](https://user-images.githubusercontent.com/69628500/219868189-eff8a0a1-4ba4-4b0f-80b3-b9d1a0ee4c9c.png)

**Comment by withrvr** [comment]
- little padding in arrows i guess
- and center align
- 
![image](https://user-images.githubusercontent.com/69628500/219868262-2f7f3718-3a33-4890-b748-5d5f5c511ab8.png)

**Comment by abhiib02** [comment]
> # 1. add links to emoji / icon ??
> ![image](https://user-images.githubusercontent.com/69628500/219866587-31ab7d74-93cc-47e3-a9ad-0e2d7eace947.png)
> Response : SvelteLogo Got its link 
> # 2. not looking/matching properlyt
> * just make it big ...
> * don't use orange color
>   ![image](https://user-images.githubusercontent.com/69628500/219866719-edf2c3f6-fc5c-400f-bb41-877084805d02.png)
> Response : Changes Done in Order to keep viewability. 
> # 3. navbar links are too small
> ![image](https://user-images.githubusercontent.com/69628500/219866773-e55e195a-b045-477d-a214-287c15e70934.png)
> Response: Links Size increased
> # 4. little CSS improvement required
> * that orange css
> * need more padding in label text
> Response: Label is on point according to me and its intended. 
> ![image](https://user-images.githubusercontent.com/69628500/219866878-00bd577b-d29e-4b07-8d8e-12775ee47a42.png)

**Comment by abhiib02** [comment]
> # also .... 404 page not there

**Added 404 page**

**Comment by abhiib02** [comment]
> ![image](https://user-images.githubusercontent.com/69628500/219868148-3918d6d3-0514-4e88-90fa-ab21c60c360c.png)
> 
> wow I saw that logo animation when I opened the image in the new tab
> 
> but not showing on-site logo animation ...... properly also make it continues/ infinite
> 
> also, make it clickable .... on the home page
> 
> ![image](https://user-images.githubusercontent.com/69628500/219868189-eff8a0a1-4ba4-4b0f-80b3-b9d1a0ee4c9c.png)

i will keep as it is Because animation in the logo i not want i want but in small scale it doesnt show up

**Comment by abhiib02** [comment]
everything in Issues is resolved and responded
